In [44]:
import numpy as np
import pandas as pd
from sktime.classification.interval_based import TimeSeriesForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score
from sktime.datasets import load_arrow_head
from sktime.datatypes import check_is_mtype
from sktime.utils import mlflow_sktime  

In [2]:
X_train_orig = pd.read_csv('X_train.csv')
y_train_orig = pd.read_csv('y_train.csv')
X_test_orig = pd.read_csv('X_test.csv')

In [37]:

label=y_train_orig.iloc[:,1]
feature=X_train_orig.iloc[:,1:].dropna(axis=1).to_numpy()
print((feature))
#valid, error_msg, metadata = check_is_mtype(feature, "univariate", return_metadata=True)

[[ -13   -9   -6 ...  -57  -57  -56]
 [ -34  110  249 ...  120  107   97]
 [ -34  -36  -37 ...   55   57   59]
 ...
 [ -95 -110 -124 ...  -64  -55  -46]
 [ -50  -48  -45 ...   -3    0    3]
 [  66   65   63 ...  -90  -92  -93]]


In [27]:
valid

False

In [28]:
error_msg

"obj must have a MultiIndex, found <class 'pandas.core.indexes.range.RangeIndex'>"

In [29]:
metadata

In [39]:
X, y = load_arrow_head()
#check_is_mtype(X, 'univariate')
print(type(X))
X_train, X_test, y_train, y_test = train_test_split(feature, label)
classifier = TimeSeriesForestClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy_score(y_test, y_pred)

<class 'pandas.core.frame.DataFrame'>


0.61953125

In [45]:
score = f1_score(y_test, y_pred, average='micro')
score

0.61953125

In [46]:
mlflow_sktime.save_model(  
    sktime_model=classifier,
    path='model')  

ModuleNotFoundError: `mlflow` is an extra dependency and is not included in the base sktime installation. Please run `pip install mlflow` or `pip install sktime[mlflow]` to install the package.